version: '3'
services:
  myapp:
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongoapp
      - redisapp
  mongoapp:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
  redisapp:
    image: redis:latest
    ports:
      - '6379:6379'
    expose:
      - 6379
    restart:
      always
volumes:
  data:
    